### ISSUE TITLE
antenna question

### ISSUE THREAD

**Issue by felmue** [QuickSpot/walter-documentation#10]
Hi guys

it is my understanding that NB-IoT uses low frequencies in order to best reach into buildings. And most countries seem to do that by using B20 (800 MHz) for NB-IoT. However the recommended antenna [Taoglas FXUB63.07.0150C](https://www.taoglas.com/product/fxub63-ultra-wide-band-flex-antenna/) for Walter is specified for 600-6000 MHz. This makes me wonder: wouldn't it make more sense to use an antenna designed for 800 MHz only?

My apologies, if that question is naive. I am a hobbyist loving to experiment with NB-IoT / LTE-M1 modems and I am trying to learn new stuff along the way.

Thanks
Felix

**Comment by daanpape** [comment]
Hi @felmue,

Thank you for your question! It's great that you're experimenting with NB-IoT and LTE-M1 modems.

To clarify, the Sequans modem in the Walter module supports frequencies ranging from 617 MHz to 2.2 GHz. This broad range allows for a single modem to be deployed globally, covering different frequency bands used in various countries.

We chose a broadband antenna, like the Taoglas FXUB63.07.0150C, to create a certified solution that can work across multiple regions without needing different hardware. This makes Walter a versatile and scalable solution for global applications.

That said, you can absolutely use an antenna specifically tuned for Band 20 (800 MHz) if you're certain that you will only be deploying Walter in that band. Such an antenna would likely be more efficient for that specific frequency, but it's important to ensure that its gain doesn’t exceed the maximum specified in the datasheet. If the gain is too high, you may need to recertify your solution to stay compliant with regulations.

Hope this helps, and happy experimenting!

Best regards,
Daan

**Comment by felmue** [comment]
Hello @daanpape 

thank you for the comprehensive explanation - this is very helpful information for me.

Best Regards
Felix
