### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by uniquepersun** [QuickSpot/walter-documentation#2]
as of the readme which I've read, it's not 5g. But it has 5g, can I get to connect to 5g and use 5g's speed. Can you clarify all? Or that's 5Gh wifi modem?

**Comment by uniquepersun** [comment]
@daanpape sorry to ping but I want to know as early as possible 🙆

**Comment by daanpape** [comment]
Hi,

5G is a collection of protocols. Walter support the low power, wide area protocols which are NB-IoT and LTE-M. These two technologies where introduced in the 4G era but continue to evolve in the 5G area. This makes Walter very future proof as Walter is going to be able to connect to 5G SA (stand-alone) networks. LTE Cat1bis for example is not future proof. 

LTE-M and NB-IoT is not about super fast speed or very low latency but all about very long range and very low power. I hope this clarifies it for you. 

Kind regards,
Daan

**Comment by uniquepersun** [comment]
ohh, thanks.
By any chance, can I get info about any docs or open sorce repo to make a board which can provide 5G high speed with low latency, actually I want to add something to my drone which will require simultaneous and continuous connection between the drne and my server

**Comment by daanpape** [comment]
True 5G high speed hardware is quite expensive but maybe the Teltonika RUTX50 is a good starting point for you? As this is out of scope for Walter I will close this issue. But please contact info@dptechnics.com if you want any technical information regarding your drone project.

Kind regards,
Daan
