### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by p2jrdbelm** [QuickSpot/walter-documentation#3]
Hi! I have just received Walter, thank you!

I understand documentation is incomplete (e.g. getting started guides for and project is still in progress. But it would be very quick and easy, and very useful if example code that you already have could be added to Repo. For example, code that is pre-loaded for https://walterdemo.quickspot.io/ demonstration. Any other code would also be very helpful.

Please can maintainers add example code

**Comment by daanpape** [comment]
Hi @p2jrdbelm, absolutely agree that documentation can be a lot better and we are working on it. A docs website is going to be added to quickspot.io in the coming month. Meanwhile I can let you know that the source code for the examples can be found here: https://github.com/QuickSpot/walter-arduino

Please let me know if this helps! And thank you for backing our Walter module!

**Comment by p2jrdbelm** [comment]
Thank you for update. very quick  this is very helpful. walter is my first time backing crowd fund project, when i found it i was amazed and cant wait to build with it. thanks for excellent project.
