### ISSUE TITLE
Antenna tuning question

### ISSUE THREAD

**Issue by felmue** [QuickSpot/walter-documentation#6]
Hi guys

when I run `at+sqnhwcfg="antennaTuning"` I get `+SQNHWCFG: antennaTuning: disable` which I understand means the antenna has not been tuned. (Which makes sense as I bought the bare Walter board and supplied my own antenna.)

Do you recommend to tune the antenna and if yes, how is that done?

Thanks
Felix

P.S. Walter connects fine to either LTE-M or NB-IoT.

**Comment by daanpape** [comment]
Hi @felmue,

The `antennaTuning` configuration parameter doesn't configure any matching for the antenna. It rather activates a certain GPIO port of the Monarch 2 modem when it is transmitting or receiving within a certain frequency band. This functionality is used when a custom PCB contains RF switches or active matching circuitry that needs to be enabled/disabled when the modem is listening on a certain frequency band.

This means that the configuration is irrelevant for Walter. 

Best regards,
Daan

**Comment by felmue** [comment]
Hello @daanpape 

ok, I see. Thank you for the explanation. I appreciate it.

Best Regards
Felix
