### ISSUE TITLE
Status LED question

### ISSUE THREAD

**Issue by felmue** [QuickSpot/walter-documentation#7]
Hi guys

I am wondering if `GPIO1/ STATUS_LED` (pad #12) is available anywhere on the Walter board?

I understand WALTER was designed with low power consumption in mind and an LED is drawing some current. That said, I personally like to have the status LED as it tells me quickly about what the modem is doing.

Thanks
Felix

**Comment by daanpape** [comment]
Hi @felmue,

We have chosen to replace the RGB LED from the Pycom GPy with a USB-C connector for programming/debugging. Therefore, if you want a LED, I would advise to connect an external LED to any of the available GPIO pins. 

Best regards,
Daan

**Comment by felmue** [comment]
Hello @daanpape 

thank you for the feedback. However I am not talking about a generic LED controlled by the ESP32S3. The Status LED (pad #12 of the modem) is controlled directly by the modem and reflects its internal state. Please see `AT+SQNLED` command.

From the description:
_The LTE LED blinks when traffic is exchanged over the air._
_Blink Mode On. The LED will blink according to the system state._

From the GM02SP Data Sheet / Rev. 9
![WalterSequansStatusLED_20240913](https://github.com/user-attachments/assets/cd673101-0803-436f-ae4a-f44b29f30e95)

Thanks
Felix

**Comment by daanpape** [comment]
Hi @felmue,

Please find the schematic of Walter here (https://github.com/QuickSpot/walter-hardware/blob/main/walter/schematic/schematic-v1.6.pdf), the status LED of the modem is not connected nor available. 

Best regards,
Daan

**Comment by felmue** [comment]
Hello @daanpape 

ok, understood. Thank you for confirming. (Maybe something to think about in the next hardware revision? E.g. adding a TP for it?)

Best regards
Felix

**Comment by daanpape** [comment]
I will add it to our 'nice-to-have' list. Adding a test pad for it seems doable. 

Best regards,
Daan
