### ISSUE TITLE
Silkscreen text for two pins incorrect

### ISSUE THREAD

**Issue by felmue** [QuickSpot/walter-documentation#8]
Hi guys

on my Walter board (v1.6) the silkscreen text for two pins is incorrect:
- GPIO01 is labelled as 11
- GPIO38 is labelled as 8

![WalterSilkscreenPin_20240913](https://github.com/user-attachments/assets/57e5cf80-4e51-44d1-a05e-e996b2547b67)

In case this is old news to you, please ignore this issue.

Thanks
Felix

**Comment by daanpape** [comment]
@felmue this is a mistake from our side and it will be corrected in the next batch. I do thank you for takin the time to report this.

Best regards,
Daan
